### PR TITLE
Updating dependencies, conforming to videojs standard

### PR DESCRIPTION
**Pull request by rigelk**
I only corrected the errors, there are still some JSDoc warnings, but apart from that the plugin runs fine and passed tests in firefox 60 and chrome 66.

### CODE REVIEW

**Comment by hartman** [comment]
@rigelk I just want to thank you and promise that once I can find some time, i'll create a new release. 

Also, don't be afraid to ping me, if I have forgotten about my promise ;)

**Comment by rigelk** [comment]
No worries, there is no hurry on my side :)

**Comment by EricTendian** [comment]
@hartman I find this plugin very useful and would appreciate an update soon so I can use it with the latest video.js 😄

**Comment by thenewguy** [comment]
Any chance for an update?

**Pull request merged**
